encoding: utf-8

baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "http://featurescrutinizer.net/" # the base hostname & protocol for your site
title: "Feature Scrutinizer"

# This is used by feed.xml. Uncomment if you want to use it.
description: "Feature discovery app for developers"

author:
  name: Marcus Clearspring
  url: /contact

paginate: 5



gems:
  - jemoji
exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"
permalink: :title
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
