encoding: utf-8

baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "http://nibl.github.io/movitos" # the base hostname & protocol for your site
title: "Movitos"

# This is used by feed.xml. Uncomment if you want to use it.
description: "Movitos: Create and produce on iOS"

podcastdescription: "Movitos: Create and produce on iOS"
keywords:
- apps
- ios
- ipad
- iphone

author:
  name: Marcus Clearspring
  url: /contact

podcast:
  owner: Wordit Limited
    name: Marcus Clearspring
    email: hello@wordit.com
  explicit: "no"
  image: http://files.ipoweruser.com/podcasts/ipoweruser_logo_256.png
  category: Technology
  subtitle: How to be seriously productive and creative on iPhone and iPad.
  defaultFileType: audio/mpeg
  year: 2015

paginate: 5



gems:
  - jemoji
exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"
permalink: :title
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
